server:
  port: 8888

spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://1.15.150.178:3306/auctionaall
    username: linwenchao
    password: 123456

  # redis配置
  redis:
    host: 139.224.11.125
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 0
    database: 0
    password: Lin058211.

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    # xml返回数据为map类型时，空值的key也要显示出来
    call-setters-on-nulls: true
  global-config:
    db-config:
      id-type: auto